import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";

import cogePalabra from "../lib/wiktionary";
import ESPANOL from "../lib/idiomas/espanol";
import Palabra from "../lib/morfologia/palabra";
// import CAMPOS from "../lib/general/campos";

export default function Home() {
  const [palabra, setPalabra] = useState("hola");
  const [palabras, setPalabras] = useState<undefined | null | Palabra[]>(
    undefined
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <input
          value={palabra}
          onChange={(e) => {
            setPalabra(e.target.value);
          }}
        />
        <button
          onClick={() => {
            const p = palabra;
            cogePalabra(palabra, ESPANOL).then(
              (resultado) => {
                if (p === palabra) setPalabras(resultado);
              },
              () => {
                if (p === palabra) setPalabras(null);
              }
            );
          }}
        >
          Haz magia
        </button>
        <p></p>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

/*
 */
